version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: echo-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass dev-redis-password
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=dev-redis-password
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "6379",
          "-a",
          "dev-redis-password",
          "ping",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
