#!/bin/bash
# =============================================================================
# generate-secrets.sh
# Generates echo-secrets.yaml for local Minikube deployment
# =============================================================================
#
# Usage:
#   ./generate-secrets.sh
#
# This script generates Kubernetes secrets that match the passwords configured
# in docker-compose.infra.yml. Infrastructure services (PostgreSQL, Redis,
# RabbitMQ) run in Docker and are accessible from Minikube via host.minikube.internal.
#
# ⚠️  IMPORTANT: The passwords below MUST match those in docker-compose.infra.yml
# If you change passwords here, you must also update docker-compose.infra.yml
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/echo-secrets.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# =============================================================================
# Configuration - MUST match docker-compose.infra.yml
# =============================================================================

# Infrastructure host (from Minikube's perspective)
INFRA_HOST="host.minikube.internal"

# PostgreSQL (running on port 5433 to avoid conflict with dev environment)
# These credentials MUST match POSTGRES_PASSWORD in docker-compose.infra.yml
POSTGRES_HOST="${INFRA_HOST}"
POSTGRES_PORT="5433"
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="postgres"

# Redis
# This password MUST match REDIS_PASSWORD in docker-compose.infra.yml
REDIS_HOST="${INFRA_HOST}"
REDIS_PORT="6379"
REDIS_PASSWORD="dev-redis-password"

# RabbitMQ
# These credentials MUST match RABBITMQ_DEFAULT_USER/PASS in docker-compose.infra.yml
RABBITMQ_HOST="${INFRA_HOST}"
RABBITMQ_PORT="5672"
RABBITMQ_USER="admin"
RABBITMQ_PASSWORD="dev-rabbitmq-password"

# JWT Secret (min 32 characters) - only used by Kubernetes services
JWT_SECRET="dev-jwt-secret-change-in-production-min-32-chars"

# Resend API Key (not used in local - MailHog via SMTP instead)
RESEND_API_KEY="re_placeholder_not_used_in_local"

# =============================================================================
# Build connection URLs
# =============================================================================
USER_DB_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/users_db?schema=public"
WC_DB_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/workspace_channels_db?schema=public"
MSG_DB_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/message_db?schema=public"
REDIS_URL="redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"
RABBITMQ_URL="amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}"

# =============================================================================
# Generate the secrets manifest
# =============================================================================
echo -e "${GREEN}Generating secrets for local Minikube deployment...${NC}"
echo ""

cat > "${OUTPUT_FILE}" << EOF
# echo-secrets.yaml
# Generated by generate-secrets.sh on $(date -Iseconds)
# ⚠️  DO NOT COMMIT TO GIT - This file is in .gitignore
#
# These values MUST match the passwords in docker-compose.infra.yml
# Infrastructure services run in Docker and are accessible via host.minikube.internal
# PostgreSQL: port ${POSTGRES_PORT}
# Redis: port ${REDIS_PORT}
# RabbitMQ: port ${RABBITMQ_PORT}
apiVersion: v1
kind: Secret
metadata:
  name: echo-secrets
  namespace: echo
  labels:
    app.kubernetes.io/part-of: echo-platform
    app.kubernetes.io/managed-by: generate-secrets-script
type: Opaque
stringData:
  # JWT Secret for token signing/verification
  JWT_SECRET: "${JWT_SECRET}"

  # Database URLs (PostgreSQL)
  USER_SERVICE_DATABASE_URL: "${USER_DB_URL}"
  WC_SERVICE_DATABASE_URL: "${WC_DB_URL}"
  MESSAGE_SERVICE_DATABASE_URL: "${MSG_DB_URL}"

  # Redis URL (for caching and Socket.IO adapter)
  REDIS_URL: "${REDIS_URL}"

  # RabbitMQ URL (for async messaging)
  RABBITMQ_URL: "${RABBITMQ_URL}"

  # Resend API Key (not used in local - using MailHog SMTP)
  RESEND_API_KEY: "${RESEND_API_KEY}"
EOF

echo -e "${GREEN}✅ Created ${OUTPUT_FILE}${NC}"
echo ""
echo "Secrets configured for:"
echo "  • PostgreSQL: postgres@${POSTGRES_HOST}:${POSTGRES_PORT}"
echo "  • Redis: ${REDIS_HOST}:${REDIS_PORT}"
echo "  • RabbitMQ: ${RABBITMQ_USER}@${RABBITMQ_HOST}:${RABBITMQ_PORT}"
echo ""
echo "Next steps:"
echo "  1. Ensure docker-compose.infra.yml is running with matching passwords"
echo "  2. Apply secrets: kubectl apply -f ${OUTPUT_FILE}"
echo "  3. Deploy application: cd .. && kubectl apply -k ."
